export default [{
    name: 'ch',
    url: 'https://coursehunter.net/fonts/icons/ch.ttf',
    weight: 400,
    style: 'normal'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansExtraBoldItalic.woff2',
    weight: 800,
    style: 'italic'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansExtraBold.woff2',
    weight: 800,
    style: 'normal'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansBoldItalic.woff2',
    weight: 700,
    style: 'italic'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansBold.woff2',
    weight: 700,
    style: 'normal'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansSemiBoldItalic.woff2',
    weight: 600,
    style: 'italic'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansSemiBold.woff2',
    weight: 600,
    style: 'normal'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansItalic.woff2',
    weight: 400,
    style: 'italic'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansRegular.woff2',
    weight: 400,
    style: 'normal'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansLightItalic.woff2',
    weight: 300,
    style: 'italic'
}, {
    name: 'Open Sans',
    url: 'https://coursehunter.net/fonts/OpenSans/OpenSansLight.woff2',
    weight: 300,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratThin.woff2',
    weight: 100,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratThinItalic.woff2',
    weight: 100,
    style: 'italic'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratExtraLight.woff2',
    weight: 200,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratExtraLightItalic.woff2',
    weight: 200,
    style: 'italic'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratLight.woff2',
    weight: 300,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratLightItalic.woff2',
    weight: 300,
    style: 'italic'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratRegular.woff2',
    weight: 400,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratItalic.woff2',
    weight: 400,
    style: 'italic'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratMedium.woff2',
    weight: 500,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratMediumItalic.woff2',
    weight: 500,
    style: 'italic'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratSemiBold.woff2',
    weight: 600,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratSemiBoldItalic.woff2',
    weight: 600,
    style: 'italic'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratBold.woff2',
    weight: 700,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratBoldItalic.woff2',
    weight: 700,
    style: 'italic'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratExtraBold.woff2',
    weight: 800,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratExtraBoldItalic.woff2',
    weight: 800,
    style: 'italic'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratBlack.woff2',
    weight: 900,
    style: 'normal'
}, {
    name: 'Montserrat',
    url: 'https://coursehunter.net/fonts/Montserrat/MontserratBlackItalic.woff2',
    weight: 900,
    style: 'italic'
}];